-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=library_conversion
TOOL_FOLDER_NAME=library_conversion
WORKFLOW_VERSION=release_29
WORKFLOW_DESCRIPTION="Workflow to convert spectral libraries to the GNPS library batch submission format"