-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=library_conversion
TOOL_FOLDER_NAME=library_conversion
WORKFLOW_VERSION=release_31
WORKFLOW_DESCRIPTION="Workflow to convert spectral libraries to the GNPS library batch submission format.\
<hr> \
<h4> Citation </h4>\
<a href='https://www.nature.com/articles/nbt.3597'>Wang, Mingxun, Jeremy J. Carver, Vanessa V. Phelan, Laura M. Sanchez, Neha Garg, Yao Peng, Don Duy Nguyen et al. 'Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking.' Nature biotechnology 34, no. 8 (2016): 828-837.</a>"