include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=ms2lda_motifdb
TOOL_FOLDER_NAME=ms2lda_motifdb
WORKFLOW_VERSION=release_31
WORKFLOW_DESCRIPTION="<img src='https://ms2lda.org/static/images/banner.png' width='600'><br> \
MS2LDA is a tool that decomposes molecular fragmentation data derived from large metabolomics experiments into annotated Mass2Motifs or discovers Mass2Motifs from experimental data. Mass2Motifs are fragmentation patterns of often co-occurring mass fragment peaks and/or neutral losses that often represent molecular substructures.\
<hr> \
<h4> Citation </h4> \
<a href='https://www.pnas.org/content/113/48/13738.short'>van Der Hooft, Justin Johan Jozias, Joe Wandy, Michael P. Barrett, Karl EV Burgess, and Simon Rogers. 'Topic modeling for untargeted substructure exploration in metabolomics.' Proceedings of the National Academy of Sciences 113, no. 48 (2016): 13738-13743.</a> \
<hr> \
<a href='https://www.nature.com/articles/nbt.3597'>Wang, Mingxun, Jeremy J. Carver, Vanessa V. Phelan, Laura M. Sanchez, Neha Garg, Yao Peng, Don Duy Nguyen et al. 'Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking.' Nature biotechnology 34, no. 8 (2016): 828-837.</a>"
