include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=ms2lda_motifdb
TOOL_FOLDER_NAME=ms2lda_motifdb
WORKFLOW_VERSION=release_24
WORKFLOW_DESCRIPTION="MS2LDA is a tool that decomposes molecular fragmentation data derived from large metabolomics experiments into annotated Mass2Motifs or discovers Mass2Motifs from experimental data. Mass2Motifs are fragmentation patterns of often co-occurring mass fragment peaks and/or neutral losses that often represent molecular substructures."
