include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=qemistree
TOOL_FOLDER_NAME=qemistree
WORKFLOW_VERSION=release_20
WORKFLOW_DESCRIPTION="Qemistree helps you visualize your data by taking into account chemical relationships between the molecules and the quantifications"