include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=cscs-ordination
TOOL_FOLDER_NAME=cscs-ordination
WORKFLOW_VERSION=release_20
WORKFLOW_DESCRIPTION="This workflow enables CSCS"

