include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=metabolomics-snets-v2
TOOL_FOLDER_NAME=metabolomicsnetsv2
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="<img src="https://gnps.ucsd.edu/ProteoSAFe/images/gnps_splash/gnps_logo.png" width="400"><br>\
Molecular networks are visual displays of the chemical space present in tandem mass spectrometry (MS/MS) experiments. \
This visualization approach can detect sets of spectra from related molecules (molecular networks), even when the spectra themselves are not \
matched to any known compounds. Classical molecular networking is well suited for discovery and can be analyzed directly from raw mass \
spectrometry files. Feature-based Molecular Networking (FBMN) is better when quantification analysis is necessary, but requires preprocessing \
with feature finding tools.<br>\
<hr> \
<h4> Citation </h4>\
<a href='https://www.nature.com/articles/nbt.3597'>Wang, M., Carver, J. J., Phelan, V. V., Sanchez, L. M., Garg, N., Peng, Y., ... & Bandeira, N. (2016). Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking. Nature biotechnology, 34(8), 828-837.</a>"

