include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=metabolomics-snets-v2
TOOL_FOLDER_NAME=metabolomicsnetsv2
WORKFLOW_VERSION=release_16
WORKFLOW_DESCRIPTION="Molecular networks are visual displays of the chemical space present in tandem mass spectrometry (MS/MS) experiments. This visualization approach can detect sets of spectra from related molecules (molecular networks), even when the spectra themselves are not matched to any known compounds."
