-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=insilico-generation
TOOL_FOLDER_NAME=insilico-generation
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="insilico-generation"
