-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=npclassifier
TOOL_FOLDER_NAME=npclassifier
WORKFLOW_VERSION=release_31
WORKFLOW_DESCRIPTION="NP-Classifer Batch Workflow.\
<hr> \
<h4> Citation </h4>\
<a href='https://pubs.acs.org/doi/abs/10.1021/acs.jnatprod.1c00399'>Kim, Hyun Woo, Mingxun Wang, Christopher A. Leber, Louis-Félix Nothias, Raphael Reher, Kyo Bin Kang, Justin JJ van der Hooft, Pieter C. Dorrestein, William H. Gerwick, and Garrison W. Cottrell. NPClassifier: A deep neural network-based structural classification tool for natural products. Journal of Natural Products (2020).</a> \
<br> \
<br> \
<a href='https://www.nature.com/articles/nbt.3597'>Wang, Mingxun, Jeremy J. Carver, Vanessa V. Phelan, Laura M. Sanchez, Neha Garg, Yao Peng, Don Duy Nguyen et al. 'Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking.' Nature biotechnology 34, no. 8 (2016): 828-837.</a>"
