-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=npclassifier
TOOL_FOLDER_NAME=npclassifier
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="NP-Classifer Batch Workflow.\
<hr> \
<h4> Citation </h4>\
<a href='https://www.nature.com/articles/nbt.3597'>Wang, Mingxun, Jeremy J. Carver, Vanessa V. Phelan, Laura M. Sanchez, Neha Garg, Yao Peng, Don Duy Nguyen et al. 'Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking.' Nature biotechnology 34, no. 8 (2016): 828-837.</a>"
