include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=molecular-librarysearch-gc
TOOL_FOLDER_NAME=molecularsearch-gc
WORKFLOW_VERSION=release_16
WORKFLOW_DESCRIPTION="Library Search and Network Generation for GC Deconvolved Spectra"
