include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=molecular-librarysearch-gc
TOOL_FOLDER_NAME=molecularsearch-gc
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="<img src="https://gnps.ucsd.edu/ProteoSAFe/images/gnps_splash/gnps_logo.png" width="400"><br>\
Library Search and Network Generation for GC Deconvolved Spectra.\
<hr> \
<h4> Citation </h4>\
<a href='https://www.nature.com/articles/s41587-020-0700-3'>Aksenov, Alexander A., Ivan Laponogov, Zheng Zhang, Sophie LF Doran, Ilaria Belluomo, Dennis Veselkov, Wout Bittremieux et al. 'Auto-deconvolution and molecular networking of gas chromatography–mass spectrometry data.' Nature biotechnology 39, no. 2 (2021): 169-173.</a>\
<hr>\
<a href='https://www.nature.com/articles/nbt.3597'>Wang, Mingxun, Jeremy J. Carver, Vanessa V. Phelan, Laura M. Sanchez, Neha Garg, Yao Peng, Don Duy Nguyen et al. 'Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking.' Nature biotechnology 34, no. 8 (2016): 828-837.</a>"
