-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=template_workflow
TOOL_FOLDER_NAME=template_workflow
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="template_workflow"
