include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=msms-chooser
TOOL_FOLDER_NAME=msms-chooser
WORKFLOW_VERSION=release_31
WORKFLOW_DESCRIPTION="MSMS-Chooser is a GNPS workflow and open-source protocol to empower the community to collect MS/MS reference data and contribute to the public MS/MS reference library.\
<hr> \
<h4> Citation </h4>\
<a href='https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/pdf/10.1002/rcm.8725?casa_token=6GeFCl0Y_YYAAAAA%3A-O7w7KNb-73RT10BtNiKDhySUVAFHrQFIxXZOiTzkZKIL-ps1m83aQqma-PnEdo59qrwOAim9qP3-g'>Vargas, Fernando, Kelly C. Weldon, Nicole Sikora, Mingxun Wang, Zheng Zhang, Emily C. Gentry, Morgan W. Panitchpakdi, Andrés Mauricio Caraballo‐Rodríguez, Pieter C. Dorrestein, and Alan K. Jarmusch. 'Protocol for community‐created public MS/MS reference spectra within the Global Natural Products Social Molecular Networking infrastructure.' Rapid Communications in Mass Spectrometry 34, no. 10 (2020): e8725.</a>\
<hr>\
<a href='https://www.nature.com/articles/nbt.3597'>Wang, Mingxun, Jeremy J. Carver, Vanessa V. Phelan, Laura M. Sanchez, Neha Garg, Yao Peng, Don Duy Nguyen et al. 'Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking.' Nature biotechnology 34, no. 8 (2016): 828-837.</a>"
