include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=msms-chooser
TOOL_FOLDER_NAME=msms-chooser
WORKFLOW_VERSION=release_29
WORKFLOW_DESCRIPTION="MSMS-Chooser is a GNPS workflow and open-source protocol to empower the community to collect MS/MS reference data and contribute to the public MS/MS reference library."
