-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=add-batch-annotated-validator
TOOL_FOLDER_NAME=add-batch-annotated-validator
WORKFLOW_VERSION=release_19
WORKFLOW_DESCRIPTION="Validator for Batch Additions"