include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=spec2vec
TOOL_FOLDER_NAME=spec2vec
WORKFLOW_VERSION=release_27
WORKFLOW_DESCRIPTION="Spec2Vec in GNPS - Spec2Vec: Improved mass spectral similarity scoring through learning of structural relationships"
