include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=molnetenhancer
TOOL_FOLDER_NAME=molnetenhancer
WORKFLOW_VERSION=release_15
WORKFLOW_DESCRIPTION="MolNetEnhancer is a workflow that enables to combine the outputs from molecular networking, MS2LDA, in silico structure annotation tools (such as Network Annotation Propagation or DEREPLICATOR) and the automated chemical classification through ClassyFire to provide a more comprehensive chemical overview of metabolomics data whilst at the same time illuminating structural details for each fragmentation spectrum."
