include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=mshub-gc
TOOL_FOLDER_NAME=mshub-gc
WORKFLOW_VERSION=release_14
WORKFLOW_DESCRIPTION="The workflow uses MSHub algorithm that conducts dataset-wide deconvolution and alignment of GC-MS data."