include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=mshub-gc
TOOL_FOLDER_NAME=mshub-gc
WORKFLOW_VERSION=release_27
WORKFLOW_DESCRIPTION="The workflow uses MSHub algorithm that conducts dataset-wide deconvolution and alignment of GC-MS data. This workflow requires a recommended minimum of 10 samples to function"
