include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=search_single_spectrum
TOOL_FOLDER_NAME=search_single_spectrum
WORKFLOW_VERSION=release_14
WORKFLOW_DESCRIPTION="Use MASST to query a single MS/MS spectrum across all public GNPS datasets. The mass spectrometry equivalent of NCBI BLAST helps to put the query spectrum in context of where else it occurs (including sample information) as well as search a single MS/MS spectrum against all public spectral libraries."
