name: workflow-unit-networking

on: [push]

jobs:
  test-networking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with nose2
      run: |
        pip install nose2
        cd metabolomics-snets-v2/test && nose2 -v && cd ../../
